"""Initial migration

Revision ID: 906987bfa85e
Revises: 
Create Date: 2025-04-18 22:53:58.276681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '906987bfa85e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_sentiment', schema=None) as batch_op:
        batch_op.drop_index('idx_date')
        batch_op.drop_index('uniq_record')

    op.drop_table('market_sentiment')
    op.drop_table('bond_rates')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('idx_active')
        batch_op.drop_index('idx_sector')

    op.drop_table('companies')
    op.drop_table('company_sentiment_profiles')
    op.drop_table('kelani_tyre_stock_prices')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('unique_prediction')

    op.drop_table('predictions')
    with op.batch_alter_table('kelani_tyre_quater_performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.String(length=10), nullable=False))
        batch_op.alter_column('quarter',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('eps',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('nav',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelani_tyre_quater_performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('nav',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('eps',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('quarter',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('ticker')

    op.create_table('predictions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('next_month_price_TYRE', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Predicted price for TYRE stock'),
    sa.Column('next_month_price_KCAB', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Predicted price for KCAB stock'),
    sa.Column('model_used', mysql.VARCHAR(length=50), nullable=True, comment='XGBoost/LSTM/DNN'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('unique_prediction', ['date', 'model_used'], unique=True)

    op.create_table('kelani_tyre_stock_prices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.DATE(), nullable=False),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('volume', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('company_sentiment_profiles',
    sa.Column('company_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('news_weight', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0.70'"), nullable=False),
    sa.Column('dividend_weight', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0.30'"), nullable=False),
    sa.Column('news_sensitivity', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'1.00'"), nullable=True, comment='Tech=1.2, Utilities=0.8'),
    sa.Column('dividend_impact_multiplier', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'1.00'"), nullable=True),
    sa.Column('negative_news_penalty', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'1.50'"), nullable=True, comment='Amplify negative news'),
    sa.Column('last_calibrated', sa.DATE(), nullable=True),
    sa.CheckConstraint('((`news_weight` + `dividend_weight`) = 1.0)', name='chk_weights'),
    sa.ForeignKeyConstraint(['company_code'], ['companies.company_code'], name='company_sentiment_profiles_ibfk_1'),
    sa.PrimaryKeyConstraint('company_code'),
    comment='Company-specific sentiment behavior rules',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Company-specific sentiment behavior rules',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('companies',
    sa.Column('company_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sector', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('industry', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('listing_date', sa.DATE(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('data_source', mysql.VARCHAR(length=20), nullable=True, comment='e.g., "CSE", "LSE", "NYSE"'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('company_code'),
    comment='Master list of all tracked companies',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Master list of all tracked companies',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_sector', ['sector'], unique=False)
        batch_op.create_index('idx_active', ['is_active'], unique=False)

    op.create_table('bond_rates',
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('open', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('high', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('low', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('market_sentiment',
    sa.Column('record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_code', mysql.VARCHAR(length=10), nullable=False, comment='Stock ticker symbol'),
    sa.Column('sentiment_date', sa.DATE(), nullable=False, comment='Date of sentiment recording'),
    sa.Column('news_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='Number of news articles'),
    sa.Column('avg_news_sentiment', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='Average sentiment (-1.0 to +1.0)'),
    sa.Column('dividend_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Dividend per share'),
    sa.Column('dividend_type', mysql.VARCHAR(length=10), nullable=True, comment='final/interim/special'),
    sa.Column('weighted_sentiment', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='Final calculated impact (-1.0 to +1.0)'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['company_code'], ['companies.company_code'], name='market_sentiment_ibfk_1'),
    sa.PrimaryKeyConstraint('record_id'),
    comment='Daily sentiment scores for stocks',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Daily sentiment scores for stocks',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('market_sentiment', schema=None) as batch_op:
        batch_op.create_index('uniq_record', ['company_code', 'sentiment_date'], unique=True)
        batch_op.create_index('idx_date', ['sentiment_date'], unique=False)

    # ### end Alembic commands ###
